import os
import stat
from pathlib import Path
import sys


def main():
    repo = Path(sys.argv[1] if len(sys.argv) > 1 else ".").resolve()
    git_dir = repo / ".git"

    if not git_dir.exists():
        print(f"Not a git repo: {repo}", file=sys.stderr)
        sys.exit(1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    tool_root = Path(__file__).parent.resolve()

    hook_map = {
        "pre-commit": tool_root / "pre-commit.sh",
        "prepare-commit-msg": tool_root / "prepare-commit-msg.sh",
    }

    for name, tool_script in hook_map.items():
        dst = hooks_dir / name

        content = f"""#!/bin/sh
# generated by install_hooks.py
exec "{tool_script}" "$@"
"""

        dst.write_text(content)
        dst.chmod(dst.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

        print(f"Installed: {dst}")

    print("Done.")


if __name__ == "__main__":
    main()
